#!/bin/bash -ex

function usage() {
    echo "Usage: $(basename $0) [BRANCH_NAME]"
    exit 1
}

HOME=/home/submit 

INI_FILE=$HOME/files/submit.ini
PID_FILE=$HOME/uwsgi.pid
STATIC_DIR=$HOME/static

branch=
if [ $# -gt 1 ]; then
    usage
elif [ $# -eq 1 ]; then
    branch=$1
fi

# Load virtual environment
if [ ! -d $HOME/venv ]; then
    virtualenv $HOME/venv
fi
source $HOME/venv/bin/activate

# Install or update submit package
if [ -z "$branch" ]; then
    pip install --upgrade submit[prod]
else
    echo "Installing submit_cs in editable mode from path on host filesystem $branch."
    pip install -e "$branch"
    # pip install --upgrade https://github.com/ucsb-cs/submit/archive/$branch.zip#egg=submit[prod]
fi

# Find Package location
PACKAGE_PATH=$(python -c 'import os, submit; print os.path.dirname(submit.__file__)')
PACKAGE_STATIC_DIR=$PACKAGE_PATH/static/

# Update static files (this sets maintenance mode)
rsync -au --delete $PACKAGE_STATIC_DIR $STATIC_DIR

# Create logs directory if it doesn't exist
if [ ! -d $HOME/logs ]; then
    mkdir $HOME/logs
fi
chmod 777 $HOME/logs

# Stop uwsgi if running
if [ -f $PID_FILE ]; then
    pid=$(cat $PID_FILE)
    if [ $? -eq 0 ]; then
        ps -p $pid > /dev/null && $(which uwsgi) --stop $PID_FILE
    fi
fi

# Stop workers
su submit -c 'killall -q worker_proxy worker_verification || true'

# Start workers
su -p submit -c 'source $HOME/venv/bin/activate; worker_verification $HOME/files/submit.ini'

for worker in worker1 worker2; do
    cp $PACKAGE_PATH/workers/worker.py /home/$worker/
    su -p submit -c "source $HOME/venv/bin/activate; worker_proxy -c restart $HOME/files/submit.ini $worker" 
done

# Reset submit user's known hosts and then test ssh from submit account
su -p submit -c 'rm -f $HOME/.ssh/known_hosts'
su submit -c "ssh -4 -oStrictHostKeyChecking=no -i $HOME/ssh_rsa worker1@localhost exit"

# Start or update application servers
$(which uwsgi) --ini-paste $INI_FILE

# Take out of maintenance mode
rm $STATIC_DIR/maintenance.html

